version: "3.8"

services:
  mongo1:
    image: mongo
    container_name: mongo1
    ports:
      - "27018:27017"
    volumes:
      - mongo1-data:/data/db
    command: ["--replSet", "rs0"]

  mongo2:
    image: mongo
    container_name: mongo2
    ports:
      - "27019:27017"
    volumes:
      - mongo2-data:/data/db
    command: ["--replSet", "rs0"]

  springboot:
    build: .
    container_name: ds
    depends_on:
      - mongo1
      - mongo2
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default

volumes:
  mongo1-data:
  mongo2-data:
